package com.example.kafka.common;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.Instant;

/**
 * Aggregated metrics generated by the Kafka Streams analytics pipeline.
 */
public record AnalyticsResult(
        @JsonProperty("type") String type,
        @JsonProperty("count") long count,
        @JsonProperty("windowStart") Instant windowStart,
        @JsonProperty("windowEnd") Instant windowEnd
) {
    @JsonCreator
    public AnalyticsResult {
    }
}
